# Generated by Django 6.0.3 on 2026-03-23 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('series', models.CharField(max_length=100)),
                ('court', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'start_date'), name='unique_tournament')],
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_of', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
                ('winner_rank', models.IntegerField()),
                ('loser_rank', models.IntegerField()),
                ('winner_set_1', models.IntegerField(blank=True, null=True)),
                ('loser_set_1', models.IntegerField(blank=True, null=True)),
                ('winner_set_2', models.IntegerField(blank=True, null=True)),
                ('loser_set_2', models.IntegerField(blank=True, null=True)),
                ('winner_set_3', models.IntegerField(blank=True, null=True)),
                ('loser_set_3', models.IntegerField(blank=True, null=True)),
                ('winner_set_4', models.IntegerField(blank=True, null=True)),
                ('loser_set_4', models.IntegerField(blank=True, null=True)),
                ('winner_set_5', models.IntegerField(blank=True, null=True)),
                ('loser_set_5', models.IntegerField(blank=True, null=True)),
                ('winner_sets', models.IntegerField(blank=True, null=True)),
                ('loser_sets', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('draw_position', models.IntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
