# Generated by Django 6.0.3 on 2026-03-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='round',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
