# Generated by Django 6.0.3 on 2026-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_matches_round'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='unique_tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tour',
            field=models.CharField(default='ATP', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='loser_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name', 'start_date', 'tour'), name='unique_tournament'),
        ),
    ]
