# Generated by Django 6.0.3 on 2026-03-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_tournament_unique_tournament_tournament_tour_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='unique_tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name', 'start_date', 'tour', 'slug'), name='unique_tournament'),
        ),
    ]
