# Generated by Django 6.0.3 on 2026-03-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_remove_tournament_unique_tournament_tournament_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='tournament.tournament'),
        ),
    ]
