# Generated by Django 6.0.3 on 2026-03-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_matches_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='tournament.tournament'),
        ),
    ]
