# Generated by Django 6.0.3 on 2026-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
