# Generated by Django 6.0.3 on 2026-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_extract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
