# Generated by Django 6.0.3 on 2026-04-14 12:03

from django.db import migrations


def add_slug(apps, schema_editor):
    Article = apps.get_model("news", "Article")
    for art in Article.objects.filter(slug=''):
        art.save()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_updated_on'),
    ]

    operations = [
        migrations.RunPython(add_slug),
    ]
