# Generated by Django 6.0.3 on 2026-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_site',
            field=models.BooleanField(default=True),
        ),
    ]
