# Generated by Django 6.0.3 on 2026-04-20 21:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_shoporder_original_basket_shoporder_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
