# Generated by Django 6.0.3 on 2026-04-14 11:56

from django.db import migrations

def add_slug(apps, schema_editor):
    Location = apps.get_model("book", "Location")
    for loc in Location.objects.filter(slug=''):
        loc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_coach_slug_court_slug_location_slug'),
    ]

    operations = [
        migrations.RunPython(add_slug),
    ]
