# Generated by Django 6.0.3 on 2026-04-16 20:07

from django.db import migrations

def add_slug(apps, schema_editor):
    Coach = apps.get_model("book", "Coach")
    for c in Coach.objects.filter(slug=''):
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20260414_1256'),
    ]

    operations = [
        migrations.RunPython(add_slug),
    ]
