# Generated by Django 6.0.3 on 2026-04-06 13:29

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('years_playing', models.IntegerField(blank=True, choices=[(1, 'Less than 1 year'), (2, '1-3 years'), (3, '3-5 years'), (4, '5-10 years'), (5, '10+ years')], null=True)),
                ('fave_surface', models.CharField(blank=True, choices=[('indoor_hard', 'Indoor Hard'), ('outdoor_hard', 'Outdoor Hard'), ('clay', 'Clay'), ('grass', 'Grass'), ('carpet', 'Carpet')], max_length=50, null=True)),
                ('fave_shot', models.CharField(blank=True, choices=[('serve', 'Serve'), ('topspin_forehand', 'Topspin Forehand'), ('slice_forehand', 'Slice Forehand'), ('flat_forehand', 'Flat Forehand'), ('topspin_backhand', 'Topspin Backhand'), ('slice_backhand', 'Slice Backhand'), ('flat_backhand', 'Flat Backhand'), ('forehand_volley', 'Forehand Volley'), ('backhand_volley', 'Backhand Volley'), ('drop_volley', 'Drop Volley'), ('smash', 'Smash'), ('half_volley', 'Half-Volley'), ('lob', 'Lob'), ('drop_shot', 'Drop Shot'), ('tweener', 'Tweener')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
